name: Test

on:
  push:
    branches: [unstable]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 🧾 Checkout source
        uses: actions/checkout@v4

      - name: 🟤 Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: 📦 Install backend dependencies
        run: bun install --frozen-lockfile

      - name: 🧪 Run tests
        run: bun run test
